---
- name: Update apt cache
  apt: update_cache=yes
  become: true
  become_user: root

- name: Install required software
  apt: name={{ item }} state=present
  become: true
  become_user: root
  with_items:
    - apache2
    - mysql-server
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb

